In [2]:
import torch
x = torch.tensor(10)
print(x)
print(x.dim())

tensor(10)
0


In [13]:
x = torch.rand(10)
x.size()

torch.Size([10])

In [16]:
temp = torch.FloatTensor([10,20,30,40.0,50.5,60.1])
temp.size()

torch.Size([6])

In [3]:
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)

a.matmul(b) 

tensor([[2491.9255, 2464.7349, 2520.2661,  ..., 2496.5791, 2479.9211,
         2510.3926],
        [2492.1648, 2469.4963, 2523.1672,  ..., 2498.3096, 2501.2529,
         2530.9197],
        [2499.1519, 2461.1057, 2524.2153,  ..., 2498.9211, 2511.1653,
         2539.7983],
        ...,
        [2492.7336, 2476.3279, 2505.9790,  ..., 2491.2263, 2500.2102,
         2522.3945],
        [2508.0039, 2473.4783, 2524.6680,  ..., 2493.6299, 2510.9709,
         2516.2083],
        [2514.5811, 2487.1362, 2543.0466,  ..., 2506.3042, 2493.1782,
         2521.9014]])

In [5]:
# GPU 지원
from torch import cuda 

if cuda.is_available(): 
    a = a.cuda()
    b = b.cuda()
    a.matmul(b)

In [9]:
from torch.autograd import Variable
x = Variable(torch.ones(2,2),requires_grad=True)
y = x.mean()

y.backward()

x.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [10]:
x.grad_fn   # Variable 객체의 grad 초기 기본값은 None이다. 
            # 변수 x와 같이 사용자가 직접 생성한 변수에서 grad_fn이 가리키는 함수 참조는 None이고,
            # 변수 y의 경우 grad_fn이 지정하는 함수 참조는 MeanBackward이다.

In [11]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [12]:
y.grad_fn

In [4]:
from torch import nn # 파이토치 신경망 구현
f = nn.Linear(17,1)
f

Linear(in_features=17, out_features=1, bias=True)

In [ ]:
# 오차 함수 구현
def loss_fn(y,y_pred):            
    loss = (y_pred-y).pow(2).sum()
    for param in [w,b]:
        if not param.grad is None: param.data.zero_() # 맨 처음은 None으로
    loss.backward()     # backward 는 학습 파라미터 w와 b의 변화 정도를 기울기로 계산
    return loss.data[0]

In [ ]:
# 옵티마이저 구현
def optimize(learning_rate):  
    w.data -= learning_rate * w.grad.data
    b.data -= learning_rate * b.grad.data

In [7]:
from torch.utils.data import Dataset

class DogsAndCataDataset(Dataset):
    def __init__(self,): # 사용자 정의 데이터셋 클래스에 테이블 인덱스 읽기와 이미지 파일명 읽기와 같은 초기화 작업이 필요하다면 
        pass            # __init__ 메서드에 구현한다. 
    def __len__(self):  # __len__ (self) 메서드는 데이터셋의 최대 요소 수를 반환한다.
        pass
    def __getitem__(self,idx): # 데이터셋에 idx번째 해당 요소를 반환한다.
        pass

In [10]:
class DogsAndCatsDataset(Dataset):
    
    def __init__(self,root_dir,size=(224,224)):
        self.files = glob(root_dir)
        self.size = size
        
    def __len__(self):
        return len(self.files)
    
    def __getitem__(self,idx):
        img = np.asarray(Image.open(self.files[idx]).resize(self.size))
        label = self.files[idx].split('/')[-2]
        return img,label

In [15]:
from torch.utils.data import Dataset, DataLoader
# 데이터셋에 딥러닝 적용